### ISSUE TITLE
Card company

### ISSUE THREAD

**Issue by leninkp** [cuperclub/cuper-front-end#4]
<img width="364" alt="card company" src="https://user-images.githubusercontent.com/7042591/57943134-df67e180-7898-11e9-9028-037b2070a1da.png">
Related with: #11

**Comment by daosgc** [comment]
Re-Open because it looks different <img width="357" alt="Captura de Pantalla 2019-05-30 a la(s) 15 59 25" src="https://user-images.githubusercontent.com/6590748/58664256-ec062400-82f3-11e9-90d5-27faae1d02aa.png">
